site_name: Meditree
repo_url: https://github.com/liplum/Meditree
repo_name: Meditree
theme:
  name: material
  logo: icon.png
  favicon: favicon.png
  icon:
    repo: fontawesome/brands/github
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 66 # p
    search: 191   # /
  features:
    - navigation.tabs
    - content.tabs.link
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

#page tree
nav:
  - Home:
    - Index: index.md

  - Backend-JS:
    - Index: backend-js/index.md

  - Interface:
    - Client Side: interface/client-side.md
    - Server Side: interface/server-side.md

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.snippets
  - meta
  - toc:
      permalink: "#"