name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: build backend-js
        run: |
          cd backend-js
          pnpm i
          pnpm build
          cd ..

      - name: build web-react
        run: |
          cd web-react
          pnpm i
          pnpm build
          cd ..

      - name: build web-vue
        run: |
          cd web-vue
          pnpm i
          pnpm build
          cd ..